### ISSUE TITLE
Unable to make it executable

### ISSUE THREAD

**Issue by seog-jun** [Rachit1313/txtToWeb#1]
Hi,

I'd like to try to use the command  chmod +x txtToWeb.py to make it executable, but it seems like not working.
Can you have a look into it? 
![image](https://github.com/Rachit1313/txtToWeb/assets/88434287/6d4fd55a-3027-477b-8b30-90661db6bd23)

Thanks

**Comment by Rachit1313** [comment]
Hi @seog-jun ,
Thank you for reaching out.

chmod is a command for bash/zsh terminal. It won't work in powershell.

Thank you.

I'll update this in readme as a requirement to use a bash terminal.
