### ISSUE TITLE
Simple typo

### ISSUE THREAD

**Issue by seog-jun** [Rachit1313/txtToWeb#2]
Hi,

On example command, your text.txt file is located in the examples directory. Add the directory name, otherwise it's not working.
fix: txtToWeb.py -s https://cdnjs.cloudflare.com/ajax/libs/tufte-css/1.8.0/tufte.min.css examples/test.txt
Also, if you show the expected result or output for every command(options), the Readme file would be nicer. 

Thanks!

**Comment by Rachit1313** [comment]
Thank you for your comment.
Actually, I moved my test.txt file and the output directory into a folder named examples later based on professor's instruction. Kindly let me know if that's okay. This is the reason I considered writing <filename> and /path/to/file for usage statements.
