### ISSUE TITLE
Break the multiple lines and not converted into the html properly

### ISSUE THREAD

**Issue by seog-jun** [Rachit1313/txtToWeb#4]
Hi,

I found out that I broke the multiple lines on the example txt file, and ran converting, but the software didn't ignore the new line and make that new line as a paragraph. Every blank line should be considered a paragraph limit and the text transformed into \<p>\</p>

![image](https://github.com/Rachit1313/txtToWeb/assets/88434287/5ff0f54a-edbb-415f-a96c-d17dae62fadb)

**Comment by Rachit1313** [comment]
Thank you for your feedback.
The issue has been fixed and committed to the main branch.
