### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by mnajibi** [Rachit1313/txtToWeb#6]
I'd like to add this feature and contribute to the project. Here's a brief overview:

What I Want to Do:

Implement Markdown support.
Ensure it integrates seamlessly.
Provide clear documentation.

Thanks,
Maryam

**Comment by Rachit1313** [comment]
Approved. Feel free to implement any changes.

**Comment by Rachit1313** [comment]
Hey, Kindly make the changes below to your PR:

1. Add more specific information in the Readme.md regarding the Italic feature
2. Mention detailed description of what you did and mention the issue number in the PR description so that it gets linked with the issue.

Thank you.
